#ifndef DALI_HEADERS_H
#define DALI_HEADERS_H

#define BROADCAST_ADDR                  0xFF

// DALI COMMAND TYPE
#define IS_NORMAL                       0x00
#define IS_QUERY                        0x01
#define IS_TWICE                        0x02

// DALI COMMANDS
#define OFF                             0x00
#define UP                              0x01
#define DOWN                            0x02
#define STEP_UP                         0x03
#define STEP_DOWN                       0x04
#define RECALL_MAX_LVL                  0x05
#define RECALL_MIN_LVL                  0x06
#define STEP_DOWN_AND_OFF               0x07
#define ON_AND_STEP_UP                  0x08
#define ENABLE_DAPC_SEQUENCE            0x09
#define GO_SCENE_0                      0x10
#define GO_SCENE_1                      0x11
#define GO_SCENE_2                      0x12
#define GO_SCENE_3                      0x13
#define GO_SCENE_4                      0x14
#define GO_SCENE_5                      0x15
#define GO_SCENE_6                      0x16
#define GO_SCENE_7                      0x17
#define GO_SCENE_8                      0x18
#define GO_SCENE_9                      0x19
#define GO_SCENE_10                     0x1A
#define GO_SCENE_11                     0x1B
#define GO_SCENE_12                     0x1C
#define GO_SCENE_13                     0x1D
#define GO_SCENE_14                     0x1E
#define GO_SCENE_15                     0x1F
#define RESET                           0x20
#define STORE_ACTUAL_LVL_DTR            0x21
#define IDENTIFY_DEVICE                 0x25
#define STORE_DTR_MAX_LVL               0x2A
#define STORE_DTR_MIN_LVL               0x2B
#define STORE_DTR_SYS_FAILURE_LVL       0x2C
#define STORE_DTR_POWER_ON_LVL          0x2D
#define STORE_DTR_FADE_TIME             0x2E
#define STORE_DTR_FADE_RATE             0x2F
#define STORE_DTR_SCENE_0               0x40
#define STORE_DTR_SCENE_1               0x41
#define STORE_DTR_SCENE_2               0x42
#define STORE_DTR_SCENE_3               0x43
#define STORE_DTR_SCENE_4               0x44
#define STORE_DTR_SCENE_5               0x45
#define STORE_DTR_SCENE_6               0x46
#define STORE_DTR_SCENE_7               0x47
#define STORE_DTR_SCENE_8               0x48
#define STORE_DTR_SCENE_9               0x49
#define STORE_DTR_SCENE_10              0x4A
#define STORE_DTR_SCENE_11              0x4B
#define STORE_DTR_SCENE_12              0x4C
#define STORE_DTR_SCENE_13              0x4D
#define STORE_DTR_SCENE_14              0x4E
#define STORE_DTR_SCENE_15              0x4F
#define REMOVE_FROM_SCENE_0             0x50
#define REMOVE_FROM_SCENE_1             0x51
#define REMOVE_FROM_SCENE_2             0x52
#define REMOVE_FROM_SCENE_3             0x53
#define REMOVE_FROM_SCENE_4             0x54
#define REMOVE_FROM_SCENE_5             0x55
#define REMOVE_FROM_SCENE_6             0x56
#define REMOVE_FROM_SCENE_7             0x57
#define REMOVE_FROM_SCENE_8             0x58
#define REMOVE_FROM_SCENE_9             0x59
#define REMOVE_FROM_SCENE_10            0x5A
#define REMOVE_FROM_SCENE_11            0x5B
#define REMOVE_FROM_SCENE_12            0x5C
#define REMOVE_FROM_SCENE_13            0x5D
#define REMOVE_FROM_SCENE_14            0x5E
#define REMOVE_FROM_SCENE_15            0x5F
#define ADD_GROUP_0                     0x60
#define ADD_GROUP_1                     0x61
#define ADD_GROUP_2                     0x62
#define ADD_GROUP_3                     0x63
#define ADD_GROUP_4                     0x64
#define ADD_GROUP_5                     0x65
#define ADD_GROUP_6                     0x66
#define ADD_GROUP_7                     0x67
#define ADD_GROUP_8                     0x68
#define ADD_GROUP_9                     0x69
#define ADD_GROUP_10                    0x6A
#define ADD_GROUP_11                    0x6B
#define ADD_GROUP_12                    0x6C
#define ADD_GROUP_13                    0x6D
#define ADD_GROUP_14                    0x6E
#define ADD_GROUP_15                    0x6F
#define REMOVE_FROM_GROUP_0             0x70
#define REMOVE_FROM_GROUP_1             0x71
#define REMOVE_FROM_GROUP_2             0x72
#define REMOVE_FROM_GROUP_3             0x73
#define REMOVE_FROM_GROUP_4             0x74
#define REMOVE_FROM_GROUP_5             0x75
#define REMOVE_FROM_GROUP_6             0x76
#define REMOVE_FROM_GROUP_7             0x77
#define REMOVE_FROM_GROUP_8             0x78
#define REMOVE_FROM_GROUP_9             0x79
#define REMOVE_FROM_GROUP_10            0x7A
#define REMOVE_FROM_GROUP_11            0x7B
#define REMOVE_FROM_GROUP_12            0x7C
#define REMOVE_FROM_GROUP_13            0x7D
#define REMOVE_FROM_GROUP_14            0x7E
#define REMOVE_FROM_GROUP_15            0x7F
#define STORE_DTR_SHORT_ADDRESS         0x80
#define ENABLE_WRITE_MEMORY             0x81
#define QUERY_STATUS                    0x90
#define QUERY_CONTROL_GEAR              0x91
#define QUERY_LAMP_FAILURE              0x92
#define QUERY_LAMP_POWER_ON             0x93
#define QUERY_LIMIT_ERROR               0x94
#define QUERY_RESET_STATE               0x95
#define QUERY_MISSING_SHORT_ADDRESS     0x96
#define QUERY_VERSION_NUMBER            0x97
#define QUERY_CONTENT_DTR_0             0x98
#define QUERY_DEVICE_TYPE               0x99
#define QUERY_PHYSICAL_MIN_LVL          0x9A
#define QUERY_POWER_FAILURE             0x9B
#define QUERY_CONTENT_DTR_1             0x9C
#define QUERY_CONTENT_DTR_2             0x9D
#define QUERY_ACTUAL_LVL                0xA0
#define QUERY_MAX_LVL                   0xA1
#define QUERY_MIN_LVL                   0xA2
#define QUERY_POWER_ON_LVL              0xA3
#define QUERY_SYSTEM_FAILURE_LVL        0xA4
#define QUERY_FADE_TIME_RATE            0xA5
#define QUERY_SCENE_LVL_0               0xB0
#define QUERY_SCENE_LVL_1               0xB1
#define QUERY_SCENE_LVL_2               0xB2
#define QUERY_SCENE_LVL_3               0xB3
#define QUERY_SCENE_LVL_4               0xB4
#define QUERY_SCENE_LVL_5               0xB5
#define QUERY_SCENE_LVL_6               0xB6
#define QUERY_SCENE_LVL_7               0xB7
#define QUERY_SCENE_LVL_8               0xB8
#define QUERY_SCENE_LVL_9               0xB9
#define QUERY_SCENE_LVL_10              0xBA
#define QUERY_SCENE_LVL_11              0xBB
#define QUERY_SCENE_LVL_12              0xBC
#define QUERY_SCENE_LVL_13              0xBD
#define QUERY_SCENE_LVL_14              0xBE
#define QUERY_SCENE_LVL_15              0xBF
#define QUERY_GROUPS_0_7                0xC0
#define QUERY_GROUPS_8_15               0xC1
#define QUERY_RANDOM_ADDRESS_HIGH       0xC2
#define QUERY_RANDOM_ADDRESS_MEDIUM     0xC3
#define QUERY_RANDOM_ADDRESS_LOW        0xC4
#define READ_MEMORY_LOCATION            0xC5

// SPECIAL COMMANDS
#define TERMINATE                       0xA1
#define DTR_0                           0xA3
#define INITIALISE                      0xA5
#define RANDOMISE                       0xA7
#define COMPARE                         0xA9
#define WITHDRAW                        0xAB
#define SEARCH_ADDRESS_HIGH             0xB1
#define SEARCH_ADDRESS_MEDIUM           0xB3
#define SEARCH_ADDRESS_LOW              0xB5
#define PROGRAM_SHORT_ADDRESS           0xB7
#define VERIFY_SHORT_ADDRESS            0xB9
#define QUERY_SHORT_ADDRESS             0xBB
#define ENABLE_DEVICE_TYPE              0xC1
#define DTR_1                           0xC3
#define DTR_2                           0xC5
#define WRITE_MEMORY_LOCATION           0xC7
#define ARC_POWER_DAPC                  0xFE

// APPLICATION EXTENDED COMMANDS
#define REST                            0xE0
#define INHIBIT                         0xE1
#define RELIGHT_RESET_INHIBIT           0xE2
#define START_FUNCTION_TEST             0xE3
#define START_DURATION_TEST             0xE4
#define STOP_TEST                       0xE5
#define RESET_FUNCTION_TEST_FLAG        0xE6
#define RESET_DURATION_TEST_FLAG        0xE7
#define RESET_LAMP_TIMER                0xE8
#define STORE_DTR_EMERGENCY_LVL         0xE9
#define STORE_TEST_DELAY_HIGH           0xEA
#define STORE_TEST_DELAY_LOW            0xEB
#define STORE_FUNCTION_TEST_INTERVAL    0xEC
#define STORE_DURATION_TEST_INTERVAL    0xED
#define STORE_TEST_EXECUTION_TIMEOUT    0xEE
#define STORE_PROLONG_TIME              0xEF
#define START_IDENTIFICATION            0xF0
#define QUERY_BATTERY_CHARGE            0xF1
#define QUERY_TEST_TIMING               0xF2
#define QUERY_DURATION_TEST_RESULT      0xF3
#define QUERY_LAMP_EMERGENCY_TIME       0xF4
#define QUERY_LAMP_OPERATION_TIME       0xF5
#define QUERY_EMERGENCY_LVL             0xF6
#define QUERY_EMERGENCY_MIN_LVL         0xF7
#define QUERY_EMERGENCY_MAX_LVL         0xF8
#define QUERY_RATED_DURATION            0xF9
#define QUERY_EMERGENCY_MODE            0xFA
#define QUERY_EMERGENCY_FEATURES        0xFB
#define QUERY_FAILURE_STATUS            0xFC
#define QUERY_EMERGENCY_STATUS          0xFD
#define PERFORM_DTR_SELECTED_FUNCTION   0xFE
#define QUERY_EXTENDED_VERSION_NUMBER   0xFF

// DALI NORMAGROUP
#define REBOOT                          0x00
#define BLINK                           0x01
#define BLINK_TERMINATE                 0x02

#endif // DALI_HEADERS_H
